### PR TITLE
Support new releases with .tgz file ending

### LINKED ISSUE #19: Failures when using
You cannot use the library without it crashing:

```
/home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/semver/semver.js:273
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 3.1.4.tgz
    at new SemVer (/home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/semver/semver.js:273:11)
    at SemVer.compare (/home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/semver/semver.js:312:13)
    at compare (/home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/semver/semver.js:460:31)
    at lt (/home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/semver/semver.js:494:10)
    at Array.filter (native)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/lib/versions.js:57:40
    at toCallback (/home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/downcache/index.js:128:2)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/downcache/index.js:112:5
    at /home/travis/.nvm/v0.10.36/lib/node_modules/mongodb-version-manager/node_modules/downcache/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:108:15)
```

The problem seems to be that the latest release 3.1.4 also has a `.tgz` file ending which is not handled.

### PR DESCRIPTION
**Pull request by ericmj**
Fixes #19.

### CODE REVIEW

**Comment by ericmj** [comment]
Ping. The library is unusable until this patch is merged.

**Comment by imlucas** [comment]
@ericmj blerg.  was on vacation.  checking it out now.

**Comment by ericmj** [comment]
Thank you! :heart:

**Comment by imlucas** [comment]
Thx @ericmj!  Just published v0.7.1

**Pull request merged**
